#!/usr/bin/env sh

##############################################################################
##
##  Encrypts keys for automated deployment.
##
##############################################################################

tar cvf deployment_keys.tar deployment_keys/
travis encrypt-file deployment_keys.tar --add
git add .travis.yml
git add deployment_keys.tar.enc
git config --global user.email "yermilov17@gmail.com"
git config --global user.name "Yaroslav Yermilov"
git commit -m "encrypt deployment keys"
git push origin
