#!/usr/bin/env sh

##############################################################################
##
##  Generates key pair for passwordless SSH connection.
##
##############################################################################

ssh-keygen -t rsa
cat .ssh/$KEY_NAME.pub >> .ssh/authorized_keys
